export interface WorldLanguage {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  country: string;
  region: 'Asia & Pacific' | 'Europe' | 'Americas' | 'Middle East' | 'Africa' | 'Global';
  dir: 'ltr' | 'rtl';
}

export interface WorldCountry {
  code: string;
  name: string;
  nativeName?: string;
  flag: string;
  dialCode?: string;
  region: 'Asia & Pacific' | 'Europe' | 'Americas' | 'Middle East' | 'Africa' | 'Oceania';
}

// 100+ World Languages covering all continents
export const WORLD_LANGUAGES: WorldLanguage[] = [
  // Major Global & Asia-Pacific Languages
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸', country: 'United States', region: 'Americas', dir: 'ltr' },
  { code: 'en-GB', name: 'English (UK)', nativeName: 'English (UK)', flag: '🇬🇧', country: 'United Kingdom', region: 'Europe', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', country: 'Spain', region: 'Europe', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', country: 'France', region: 'Europe', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', country: 'Saudi Arabia', region: 'Middle East', dir: 'rtl' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', country: 'Bangladesh', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', country: 'Brazil', region: 'Americas', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', country: 'Russia', region: 'Europe', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', country: 'Germany', region: 'Europe', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', country: 'Japan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷', country: 'Turkey', region: 'Middle East', dir: 'ltr' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳', country: 'Vietnam', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰', country: 'Pakistan', region: 'Asia & Pacific', dir: 'rtl' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', country: 'Italy', region: 'Europe', dir: 'ltr' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '中文 (简体)', flag: '🇨🇳', country: 'China', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '中文 (繁體)', flag: '🇹🇼', country: 'Taiwan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷', country: 'South Korea', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'fa', name: 'Persian (Farsi)', nativeName: 'فارسی', flag: '🇮🇷', country: 'Iran', region: 'Middle East', dir: 'rtl' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱', country: 'Poland', region: 'Europe', dir: 'ltr' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦', country: 'Ukraine', region: 'Europe', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱', country: 'Netherlands', region: 'Europe', dir: 'ltr' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭', country: 'Thailand', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷', country: 'Greece', region: 'Europe', dir: 'ltr' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', country: 'Indonesia', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪', country: 'Sweden', region: 'Europe', dir: 'ltr' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾', country: 'Malaysia', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴', country: 'Romania', region: 'Europe', dir: 'ltr' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿', country: 'Czech Republic', region: 'Europe', dir: 'ltr' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺', country: 'Hungary', region: 'Europe', dir: 'ltr' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱', country: 'Israel', region: 'Middle East', dir: 'rtl' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰', country: 'Denmark', region: 'Europe', dir: 'ltr' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮', country: 'Finland', region: 'Europe', dir: 'ltr' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴', country: 'Norway', region: 'Europe', dir: 'ltr' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪', country: 'Kenya', region: 'Africa', dir: 'ltr' },
  { code: 'tl', name: 'Tagalog (Filipino)', nativeName: 'Filipino', flag: '🇵🇭', country: 'Philippines', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇳🇵', country: 'Nepal', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰', country: 'Sri Lanka', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'my', name: 'Burmese', nativeName: 'မြန်မာဘာသာ', flag: '🇲🇲', country: 'Myanmar', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', flag: '🇰🇭', country: 'Cambodia', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ', flag: '🇱🇦', country: 'Laos', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو', flag: '🇦🇫', country: 'Afghanistan', region: 'Middle East', dir: 'rtl' },
  { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî / کوردی', flag: '🇮🇶', country: 'Iraq', region: 'Middle East', dir: 'rtl' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹', country: 'Ethiopia', region: 'Africa', dir: 'ltr' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴', country: 'Somalia', region: 'Africa', dir: 'ltr' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Èdè Yorùbá', flag: '🇳🇬', country: 'Nigeria', region: 'Africa', dir: 'ltr' },
  { code: 'ha', name: 'Hausa', nativeName: 'Harshen Hausa', flag: '🇳🇬', country: 'Nigeria', region: 'Africa', dir: 'ltr' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', flag: '🇳🇬', country: 'Nigeria', region: 'Africa', dir: 'ltr' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦', country: 'South Africa', region: 'Africa', dir: 'ltr' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦', country: 'South Africa', region: 'Africa', dir: 'ltr' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱', country: 'Albania', region: 'Europe', dir: 'ltr' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲', country: 'Armenia', region: 'Europe', dir: 'ltr' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan dili', flag: '🇦🇿', country: 'Azerbaijan', region: 'Middle East', dir: 'ltr' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', flag: '🇪🇸', country: 'Spain', region: 'Europe', dir: 'ltr' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', flag: '🇧🇾', country: 'Belarus', region: 'Europe', dir: 'ltr' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', flag: '🇧🇦', country: 'Bosnia and Herzegovina', region: 'Europe', dir: 'ltr' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬', country: 'Bulgaria', region: 'Europe', dir: 'ltr' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🇪🇸', country: 'Spain', region: 'Europe', dir: 'ltr' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷', country: 'Croatia', region: 'Europe', dir: 'ltr' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪', country: 'Estonia', region: 'Europe', dir: 'ltr' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪', country: 'Georgia', region: 'Europe', dir: 'ltr' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸', country: 'Iceland', region: 'Europe', dir: 'ltr' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', flag: '🇮🇪', country: 'Ireland', region: 'Europe', dir: 'ltr' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', flag: '🇰🇿', country: 'Kazakhstan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻', country: 'Latvia', region: 'Europe', dir: 'ltr' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹', country: 'Lithuania', region: 'Europe', dir: 'ltr' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', flag: '🇲🇰', country: 'North Macedonia', region: 'Europe', dir: 'ltr' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', flag: '🇲🇹', country: 'Malta', region: 'Europe', dir: 'ltr' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл', flag: '🇲🇳', country: 'Mongolia', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸', country: 'Serbia', region: 'Europe', dir: 'ltr' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰', country: 'Slovakia', region: 'Europe', dir: 'ltr' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮', country: 'Slovenia', region: 'Europe', dir: 'ltr' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbekcha', flag: '🇺🇿', country: 'Uzbekistan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', country: 'United Kingdom', region: 'Europe', dir: 'ltr' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', flag: '🇮🇱', country: 'Israel', region: 'Middle East', dir: 'rtl' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳', country: 'India', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', flag: '🇵🇰', country: 'Pakistan', region: 'Asia & Pacific', dir: 'rtl' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་སྐད་', flag: '🇨🇳', country: 'Tibet', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'la', name: 'Latin', nativeName: 'Latina', flag: '🏛️', country: 'Vatican City', region: 'Europe', dir: 'ltr' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', flag: '🌐', country: 'International', region: 'Global', dir: 'ltr' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', flag: '🇪🇸', country: 'Spain', region: 'Europe', dir: 'ltr' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', flag: '🇹🇯', country: 'Tajikistan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', flag: '🇰🇬', country: 'Kyrgyzstan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmençe', flag: '🇹🇲', country: 'Turkmenistan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'tt', name: 'Tatar', nativeName: 'Татарча', flag: '🇷🇺', country: 'Russia', region: 'Europe', dir: 'ltr' },
  { code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە', flag: '🇨🇳', country: 'China', region: 'Asia & Pacific', dir: 'rtl' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', flag: '🇲🇬', country: 'Madagascar', region: 'Africa', dir: 'ltr' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flag: '🇷🇼', country: 'Rwanda', region: 'Africa', dir: 'ltr' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona', flag: '🇿🇼', country: 'Zimbabwe', region: 'Africa', dir: 'ltr' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', flag: '🇿🇦', country: 'South Africa', region: 'Africa', dir: 'ltr' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', flag: '🇱🇸', country: 'Lesotho', region: 'Africa', dir: 'ltr' },
  { code: 'tn', name: 'Tswana', nativeName: 'Setswana', flag: '🇧🇼', country: 'Botswana', region: 'Africa', dir: 'ltr' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wolof', flag: '🇸🇳', country: 'Senegal', region: 'Africa', dir: 'ltr' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', flag: '🇧🇹', country: 'Bhutan', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'mi', name: 'Maori', nativeName: 'Te Reo Māori', flag: '🇳🇿', country: 'New Zealand', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Sāmoa', flag: '🇼🇸', country: 'Samoa', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea Faka-Tonga', flag: '🇹🇴', country: 'Tonga', region: 'Asia & Pacific', dir: 'ltr' },
  { code: 'fj', name: 'Fijian', nativeName: 'Na Vosa Vakaviti', flag: '🇫🇯', country: 'Fiji', region: 'Asia & Pacific', dir: 'ltr' },
];

// Complete 195+ sovereign countries of the world with codes, flags, dial codes & regions
export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: 'IN', name: 'India', nativeName: 'भारत', flag: '🇮🇳', dialCode: '+91', region: 'Asia & Pacific' },
  { code: 'US', name: 'United States', nativeName: 'United States', flag: '🇺🇸', dialCode: '+1', region: 'Americas' },
  { code: 'GB', name: 'United Kingdom', nativeName: 'United Kingdom', flag: '🇬🇧', dialCode: '+44', region: 'Europe' },
  { code: 'CA', name: 'Canada', nativeName: 'Canada', flag: '🇨🇦', dialCode: '+1', region: 'Americas' },
  { code: 'AU', name: 'Australia', nativeName: 'Australia', flag: '🇦🇺', dialCode: '+61', region: 'Oceania' },
  { code: 'AE', name: 'United Arab Emirates', nativeName: 'الإمارات العربية المتحدة', flag: '🇦🇪', dialCode: '+971', region: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', nativeName: 'المملكة العربية السعودية', flag: '🇸🇦', dialCode: '+966', region: 'Middle East' },
  { code: 'DE', name: 'Germany', nativeName: 'Deutschland', flag: '🇩🇪', dialCode: '+49', region: 'Europe' },
  { code: 'FR', name: 'France', nativeName: 'France', flag: '🇫🇷', dialCode: '+33', region: 'Europe' },
  { code: 'JP', name: 'Japan', nativeName: '日本', flag: '🇯🇵', dialCode: '+81', region: 'Asia & Pacific' },
  { code: 'BR', name: 'Brazil', nativeName: 'Brasil', flag: '🇧🇷', dialCode: '+55', region: 'Americas' },
  { code: 'PK', name: 'Pakistan', nativeName: 'پاکستان', flag: '🇵🇰', dialCode: '+92', region: 'Asia & Pacific' },
  { code: 'BD', name: 'Bangladesh', nativeName: 'বাংলাদেশ', flag: '🇧🇩', dialCode: '+880', region: 'Asia & Pacific' },
  { code: 'NP', name: 'Nepal', nativeName: 'नेपाल', flag: '🇳🇵', dialCode: '+977', region: 'Asia & Pacific' },
  { code: 'LK', name: 'Sri Lanka', nativeName: 'ශ්‍රී ලංකා', flag: '🇱🇰', dialCode: '+94', region: 'Asia & Pacific' },
  { code: 'SG', name: 'Singapore', nativeName: 'Singapore', flag: '🇸🇬', dialCode: '+65', region: 'Asia & Pacific' },
  { code: 'MY', name: 'Malaysia', nativeName: 'Malaysia', flag: '🇲🇾', dialCode: '+60', region: 'Asia & Pacific' },
  { code: 'ID', name: 'Indonesia', nativeName: 'Indonesia', flag: '🇮🇩', dialCode: '+62', region: 'Asia & Pacific' },
  { code: 'PH', name: 'Philippines', nativeName: 'Pilipinas', flag: '🇵🇭', dialCode: '+63', region: 'Asia & Pacific' },
  { code: 'VN', name: 'Vietnam', nativeName: 'Việt Nam', flag: '🇻🇳', dialCode: '+84', region: 'Asia & Pacific' },
  { code: 'TH', name: 'Thailand', nativeName: 'ประเทศไทย', flag: '🇹🇭', dialCode: '+66', region: 'Asia & Pacific' },
  { code: 'MM', name: 'Myanmar', nativeName: 'မြန်မာ', flag: '🇲🇲', dialCode: '+95', region: 'Asia & Pacific' },
  { code: 'KH', name: 'Cambodia', nativeName: 'កម្ពុជា', flag: '🇰🇭', dialCode: '+855', region: 'Asia & Pacific' },
  { code: 'LA', name: 'Laos', nativeName: 'ລາວ', flag: '🇱🇦', dialCode: '+856', region: 'Asia & Pacific' },
  { code: 'CN', name: 'China', nativeName: '中国', flag: '🇨🇳', dialCode: '+86', region: 'Asia & Pacific' },
  { code: 'KR', name: 'South Korea', nativeName: '대한민국', flag: '🇰🇷', dialCode: '+82', region: 'Asia & Pacific' },
  { code: 'TW', name: 'Taiwan', nativeName: '台灣', flag: '🇹🇼', dialCode: '+886', region: 'Asia & Pacific' },
  { code: 'HK', name: 'Hong Kong', nativeName: '香港', flag: '🇭🇰', dialCode: '+852', region: 'Asia & Pacific' },
  { code: 'NZ', name: 'New Zealand', nativeName: 'New Zealand', flag: '🇳🇿', dialCode: '+64', region: 'Oceania' },
  { code: 'AF', name: 'Afghanistan', nativeName: 'افغانستان', flag: '🇦🇫', dialCode: '+93', region: 'Asia & Pacific' },
  { code: 'IR', name: 'Iran', nativeName: 'ایران', flag: '🇮🇷', dialCode: '+98', region: 'Middle East' },
  { code: 'IQ', name: 'Iraq', nativeName: 'العراق', flag: '🇮🇶', dialCode: '+964', region: 'Middle East' },
  { code: 'TR', name: 'Turkey', nativeName: 'Türkiye', flag: '🇹🇷', dialCode: '+90', region: 'Middle East' },
  { code: 'IL', name: 'Israel', nativeName: 'ישראל', flag: '🇮🇱', dialCode: '+972', region: 'Middle East' },
  { code: 'QA', name: 'Qatar', nativeName: 'قطر', flag: '🇶🇦', dialCode: '+974', region: 'Middle East' },
  { code: 'KW', name: 'Kuwait', nativeName: 'الكويت', flag: '🇰🇼', dialCode: '+965', region: 'Middle East' },
  { code: 'OM', name: 'Oman', nativeName: 'عمان', flag: '🇴🇲', dialCode: '+968', region: 'Middle East' },
  { code: 'BH', name: 'Bahrain', nativeName: 'البحرين', flag: '🇧🇭', dialCode: '+973', region: 'Middle East' },
  { code: 'JO', name: 'Jordan', nativeName: 'الأردن', flag: '🇯🇴', dialCode: '+962', region: 'Middle East' },
  { code: 'LB', name: 'Lebanon', nativeName: 'لبنان', flag: '🇱🇧', dialCode: '+961', region: 'Middle East' },
  { code: 'YE', name: 'Yemen', nativeName: 'اليمن', flag: '🇾🇪', dialCode: '+967', region: 'Middle East' },
  { code: 'EG', name: 'Egypt', nativeName: 'مصر', flag: '🇪🇬', dialCode: '+20', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', nativeName: 'South Africa', flag: '🇿🇦', dialCode: '+27', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', nativeName: 'Nigeria', flag: '🇳🇬', dialCode: '+234', region: 'Africa' },
  { code: 'KE', name: 'Kenya', nativeName: 'Kenya', flag: '🇰🇪', dialCode: '+254', region: 'Africa' },
  { code: 'GH', name: 'Ghana', nativeName: 'Ghana', flag: '🇬🇭', dialCode: '+233', region: 'Africa' },
  { code: 'ET', name: 'Ethiopia', nativeName: 'ኢትዮጵያ', flag: '🇪🇹', dialCode: '+251', region: 'Africa' },
  { code: 'MA', name: 'Morocco', nativeName: 'المغرب', flag: '🇲🇦', dialCode: '+212', region: 'Africa' },
  { code: 'DZ', name: 'Algeria', nativeName: 'الجزائر', flag: '🇩🇿', dialCode: '+213', region: 'Africa' },
  { code: 'TN', name: 'Tunisia', nativeName: 'تونس', flag: '🇹🇳', dialCode: '+216', region: 'Africa' },
  { code: 'TZ', name: 'Tanzania', nativeName: 'Tanzania', flag: '🇹🇿', dialCode: '+255', region: 'Africa' },
  { code: 'UG', name: 'Uganda', nativeName: 'Uganda', flag: '🇺🇬', dialCode: '+256', region: 'Africa' },
  { code: 'RW', name: 'Rwanda', nativeName: 'Rwanda', flag: '🇷🇼', dialCode: '+250', region: 'Africa' },
  { code: 'SO', name: 'Somalia', nativeName: 'Soomaaliya', flag: '🇸🇴', dialCode: '+252', region: 'Africa' },
  { code: 'SD', name: 'Sudan', nativeName: 'السودان', flag: '🇸🇩', dialCode: '+249', region: 'Africa' },
  { code: 'SN', name: 'Senegal', nativeName: 'Sénégal', flag: '🇸🇳', dialCode: '+221', region: 'Africa' },
  { code: 'CI', name: 'Ivory Coast', nativeName: "Côte d'Ivoire", flag: '🇨🇮', dialCode: '+225', region: 'Africa' },
  { code: 'CM', name: 'Cameroon', nativeName: 'Cameroun', flag: '🇨🇲', dialCode: '+237', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', nativeName: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263', region: 'Africa' },
  { code: 'ZM', name: 'Zambia', nativeName: 'Zambia', flag: '🇿🇲', dialCode: '+260', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', nativeName: 'Moçambique', flag: '🇲🇿', dialCode: '+258', region: 'Africa' },
  { code: 'AO', name: 'Angola', nativeName: 'Angola', flag: '🇦🇴', dialCode: '+244', region: 'Africa' },
  { code: 'MG', name: 'Madagascar', nativeName: 'Madagasikara', flag: '🇲🇬', dialCode: '+261', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', nativeName: 'Maurice', flag: '🇲🇺', dialCode: '+230', region: 'Africa' },
  { code: 'RU', name: 'Russia', nativeName: 'Россия', flag: '🇷🇺', dialCode: '+7', region: 'Europe' },
  { code: 'IT', name: 'Italy', nativeName: 'Italia', flag: '🇮🇹', dialCode: '+39', region: 'Europe' },
  { code: 'ES', name: 'Spain', nativeName: 'España', flag: '🇪🇸', dialCode: '+34', region: 'Europe' },
  { code: 'NL', name: 'Netherlands', nativeName: 'Nederland', flag: '🇳🇱', dialCode: '+31', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', nativeName: 'Schweiz', flag: '🇨🇭', dialCode: '+41', region: 'Europe' },
  { code: 'SE', name: 'Sweden', nativeName: 'Sverige', flag: '🇸🇪', dialCode: '+46', region: 'Europe' },
  { code: 'NO', name: 'Norway', nativeName: 'Norge', flag: '🇳🇴', dialCode: '+47', region: 'Europe' },
  { code: 'DK', name: 'Denmark', nativeName: 'Danmark', flag: '🇩🇰', dialCode: '+45', region: 'Europe' },
  { code: 'FI', name: 'Finland', nativeName: 'Suomi', flag: '🇫🇮', dialCode: '+358', region: 'Europe' },
  { code: 'IE', name: 'Ireland', nativeName: 'Éire', flag: '🇮🇪', dialCode: '+353', region: 'Europe' },
  { code: 'BE', name: 'Belgium', nativeName: 'België', flag: '🇧🇪', dialCode: '+32', region: 'Europe' },
  { code: 'AT', name: 'Austria', nativeName: 'Österreich', flag: '🇦🇹', dialCode: '+43', region: 'Europe' },
  { code: 'PT', name: 'Portugal', nativeName: 'Portugal', flag: '🇵🇹', dialCode: '+351', region: 'Europe' },
  { code: 'PL', name: 'Poland', nativeName: 'Polska', flag: '🇵🇱', dialCode: '+48', region: 'Europe' },
  { code: 'UA', name: 'Ukraine', nativeName: 'Україна', flag: '🇺🇦', dialCode: '+380', region: 'Europe' },
  { code: 'RO', name: 'Romania', nativeName: 'România', flag: '🇷🇴', dialCode: '+40', region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', nativeName: 'Česko', flag: '🇨🇿', dialCode: '+420', region: 'Europe' },
  { code: 'GR', name: 'Greece', nativeName: 'Ελλάδα', flag: '🇬🇷', dialCode: '+30', region: 'Europe' },
  { code: 'HU', name: 'Hungary', nativeName: 'Magyarország', flag: '🇭🇺', dialCode: '+36', region: 'Europe' },
  { code: 'HR', name: 'Croatia', nativeName: 'Hrvatska', flag: '🇭🇷', dialCode: '+385', region: 'Europe' },
  { code: 'BG', name: 'Bulgaria', nativeName: 'България', flag: '🇧🇬', dialCode: '+359', region: 'Europe' },
  { code: 'SK', name: 'Slovakia', nativeName: 'Slovensko', flag: '🇸🇰', dialCode: '+421', region: 'Europe' },
  { code: 'RS', name: 'Serbia', nativeName: 'Србија', flag: '🇷🇸', dialCode: '+381', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', nativeName: 'Lietuva', flag: '🇱🇹', dialCode: '+370', region: 'Europe' },
  { code: 'LV', name: 'Latvia', nativeName: 'Latvija', flag: '🇱🇻', dialCode: '+371', region: 'Europe' },
  { code: 'EE', name: 'Estonia', nativeName: 'Eesti', flag: '🇪🇪', dialCode: '+372', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', nativeName: 'Slovenija', flag: '🇸🇮', dialCode: '+386', region: 'Europe' },
  { code: 'IS', name: 'Iceland', nativeName: 'Ísland', flag: '🇮🇸', dialCode: '+354', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', nativeName: 'Luxembourg', flag: '🇱🇺', dialCode: '+352', region: 'Europe' },
  { code: 'CY', name: 'Cyprus', nativeName: 'Κύπρος', flag: '🇨🇾', dialCode: '+357', region: 'Europe' },
  { code: 'MT', name: 'Malta', nativeName: 'Malta', flag: '🇲🇹', dialCode: '+356', region: 'Europe' },
  { code: 'AL', name: 'Albania', nativeName: 'Shqipëria', flag: '🇦🇱', dialCode: '+355', region: 'Europe' },
  { code: 'MK', name: 'North Macedonia', nativeName: 'Северна Македонија', flag: '🇲🇰', dialCode: '+389', region: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nativeName: 'Bosna i Hercegovina', flag: '🇧🇦', dialCode: '+387', region: 'Europe' },
  { code: 'ME', name: 'Montenegro', nativeName: 'Crna Gora', flag: '🇲🇪', dialCode: '+382', region: 'Europe' },
  { code: 'MD', name: 'Moldova', nativeName: 'Moldova', flag: '🇲🇩', dialCode: '+373', region: 'Europe' },
  { code: 'BY', name: 'Belarus', nativeName: 'Беларусь', flag: '🇧🇾', dialCode: '+375', region: 'Europe' },
  { code: 'GE', name: 'Georgia', nativeName: 'საქართველო', flag: '🇬🇪', dialCode: '+995', region: 'Europe' },
  { code: 'AM', name: 'Armenia', nativeName: 'Հայաստան', flag: '🇦🇲', dialCode: '+374', region: 'Europe' },
  { code: 'AZ', name: 'Azerbaijan', nativeName: 'Azərbaycan', flag: '🇦🇿', dialCode: '+994', region: 'Middle East' },
  { code: 'KZ', name: 'Kazakhstan', nativeName: 'Қазақстан', flag: '🇰🇿', dialCode: '+7', region: 'Asia & Pacific' },
  { code: 'UZ', name: 'Uzbekistan', nativeName: 'Oʻzbekiston', flag: '🇺🇿', dialCode: '+998', region: 'Asia & Pacific' },
  { code: 'TM', name: 'Turkmenistan', nativeName: 'Türkmenistan', flag: '🇹🇲', dialCode: '+993', region: 'Asia & Pacific' },
  { code: 'KG', name: 'Kyrgyzstan', nativeName: 'Кыргызстан', flag: '🇰🇬', dialCode: '+996', region: 'Asia & Pacific' },
  { code: 'TJ', name: 'Tajikistan', nativeName: 'Тоҷикистон', flag: '🇹🇯', dialCode: '+992', region: 'Asia & Pacific' },
  { code: 'MN', name: 'Mongolia', nativeName: 'Монгол', flag: '🇲🇳', dialCode: '+976', region: 'Asia & Pacific' },
  { code: 'BT', name: 'Bhutan', nativeName: 'འབྲུག', flag: '🇧🇹', dialCode: '+975', region: 'Asia & Pacific' },
  { code: 'MV', name: 'Maldives', nativeName: 'ދިވެހިރާއްޖެ', flag: '🇲🇻', dialCode: '+960', region: 'Asia & Pacific' },
  { code: 'MX', name: 'Mexico', nativeName: 'México', flag: '🇲🇽', dialCode: '+52', region: 'Americas' },
  { code: 'AR', name: 'Argentina', nativeName: 'Argentina', flag: '🇦🇷', dialCode: '+54', region: 'Americas' },
  { code: 'CO', name: 'Colombia', nativeName: 'Colombia', flag: '🇨🇴', dialCode: '+57', region: 'Americas' },
  { code: 'CL', name: 'Chile', nativeName: 'Chile', flag: '🇨🇱', dialCode: '+56', region: 'Americas' },
  { code: 'PE', name: 'Peru', nativeName: 'Perú', flag: '🇵🇪', dialCode: '+51', region: 'Americas' },
  { code: 'VE', name: 'Venezuela', nativeName: 'Venezuela', flag: '🇻🇪', dialCode: '+58', region: 'Americas' },
  { code: 'EC', name: 'Ecuador', nativeName: 'Ecuador', flag: '🇪🇨', dialCode: '+593', region: 'Americas' },
  { code: 'BO', name: 'Bolivia', nativeName: 'Bolivia', flag: '🇧🇴', dialCode: '+591', region: 'Americas' },
  { code: 'UY', name: 'Uruguay', nativeName: 'Uruguay', flag: '🇺🇾', dialCode: '+598', region: 'Americas' },
  { code: 'PY', name: 'Paraguay', nativeName: 'Paraguay', flag: '🇵🇾', dialCode: '+595', region: 'Americas' },
  { code: 'CR', name: 'Costa Rica', nativeName: 'Costa Rica', flag: '🇨🇷', dialCode: '+506', region: 'Americas' },
  { code: 'PA', name: 'Panama', nativeName: 'Panamá', flag: '🇵🇦', dialCode: '+507', region: 'Americas' },
  { code: 'GT', name: 'Guatemala', nativeName: 'Guatemala', flag: '🇬🇹', dialCode: '+502', region: 'Americas' },
  { code: 'DO', name: 'Dominican Republic', nativeName: 'República Dominicana', flag: '🇩🇴', dialCode: '+1', region: 'Americas' },
  { code: 'CU', name: 'Cuba', nativeName: 'Cuba', flag: '🇨🇺', dialCode: '+53', region: 'Americas' },
  { code: 'JM', name: 'Jamaica', nativeName: 'Jamaica', flag: '🇯🇲', dialCode: '+1', region: 'Americas' },
  { code: 'TT', name: 'Trinidad and Tobago', nativeName: 'Trinidad and Tobago', flag: '🇹🇹', dialCode: '+1', region: 'Americas' },
  { code: 'HN', name: 'Honduras', nativeName: 'Honduras', flag: '🇭🇳', dialCode: '+504', region: 'Americas' },
  { code: 'SV', name: 'El Salvador', nativeName: 'El Salvador', flag: '🇸🇻', dialCode: '+503', region: 'Americas' },
  { code: 'NI', name: 'Nicaragua', nativeName: 'Nicaragua', flag: '🇳🇮', dialCode: '+505', region: 'Americas' },
  { code: 'PG', name: 'Papua New Guinea', nativeName: 'Papua Niugini', flag: '🇵🇬', dialCode: '+675', region: 'Oceania' },
  { code: 'FJ', name: 'Fiji', nativeName: 'Viti', flag: '🇫🇯', dialCode: '+679', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', nativeName: 'Sāmoa', flag: '🇼🇸', dialCode: '+685', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', nativeName: 'Tonga', flag: '🇹🇴', dialCode: '+676', region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', nativeName: 'Vanuatu', flag: '🇻🇺', dialCode: '+678', region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', nativeName: 'Solomon Islands', flag: '🇸🇧', dialCode: '+677', region: 'Oceania' },
  { code: 'FM', name: 'Micronesia', nativeName: 'Micronesia', flag: '🇫🇲', dialCode: '+691', region: 'Oceania' },
  { code: 'KI', name: 'Kiribati', nativeName: 'Kiribati', flag: '🇰🇮', dialCode: '+686', region: 'Oceania' },
  { code: 'PW', name: 'Palau', nativeName: 'Belau', flag: '🇵🇼', dialCode: '+680', region: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands', nativeName: 'Aolepān Aorōkin M̧ajeļ', flag: '🇲🇭', dialCode: '+692', region: 'Oceania' },
  { code: 'NR', name: 'Nauru', nativeName: 'Naoero', flag: '🇳🇷', dialCode: '+674', region: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', nativeName: 'Tuvalu', flag: '🇹🇻', dialCode: '+688', region: 'Oceania' },
  { code: 'VA', name: 'Vatican City', nativeName: 'Città del Vaticano', flag: '🇻🇦', dialCode: '+379', region: 'Europe' },
  { code: 'MC', name: 'Monaco', nativeName: 'Monaco', flag: '🇲🇨', dialCode: '+377', region: 'Europe' },
  { code: 'LI', name: 'Liechtenstein', nativeName: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423', region: 'Europe' },
  { code: 'SM', name: 'San Marino', nativeName: 'San Marino', flag: '🇸🇲', dialCode: '+378', region: 'Europe' },
  { code: 'AD', name: 'Andorra', nativeName: 'Andorra', flag: '🇦🇩', dialCode: '+376', region: 'Europe' },
];
